In [2]:
import numpy as np

In [10]:
# using slice function
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
s

[0 1 2 3 4 5 6 7 8 9]


slice(2, 7, 2)

In [11]:
# slicing using index
import numpy as np 
a = np.arange(10)
print(a)
b = a[2:7:2] 
b

[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [9]:
# slicing single item

a = np.arange(10) 
print(a)
b = a[5] 
b

[0 1 2 3 4 5 6 7 8 9]


5

In [13]:
# slice items starting from index 
a = np.arange(10) 
print(a)
a[4:]

[0 1 2 3 4 5 6 7 8 9]


array([4, 5, 6, 7, 8, 9])

In [14]:
# slice items between indexes 

a = np.arange(10) 
print(a)
a[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [17]:

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [26]:


# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:') 
print(a[...,1])
print('\n')

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,...])
print('\n') 

# Now we will slice all items from column 1 onwards 
print("The items column 1 onwards are:")
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
